name: woedpress_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  provider: ^6.1.2
  dio: ^5.5.0
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0
  collection: ^1.17.2
  intl: ^0.19.0
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.3
  loading_animation_widget: ^1.3.0
  shamsi_date: ^1.0.4
  # persistent_bottom_nav_bar: ^6.2.1
  flutter_secure_storage: ^9.2.2
  persistent_bottom_nav_bar_v2: ^5.2.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Iransans
      fonts:
        - asset: assets/fonts/Iranian_Sans.ttf

    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar.ttf
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh.ttf